/**
 * This file is auto-generated by scripts/generate-build-info.js
 * Do not edit manually.
 */
export const BUILD_INFO = {
  version: '0.0.0-local',
  buildNumber: 'local-dev',
  buildDate: new Date().toISOString(),
  branch: 'local',
  commit: 'unknown',
  tag: 'none',
  environment: 'development',
  angularVersion: 'unknown'
} as const;



